version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-book-management
    ports:
      - "8080:80"
    restart: unless-stopped
    # 如果需要环境变量，可以在这里添加
    # environment:
    #   - NODE_ENV=production
    # 如果需要挂载卷，可以在这里添加
    # volumes:
    #   - ./logs:/var/log/nginx